import org.kohsuke.args4j.CmdLineException;
import org.kohsuke.args4j.CmdLineParser;
import org.kohsuke.args4j.Option;
import org.netbeans.lib.profiler.heap.*;
import java.io.*;
import java.util.List;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	
	@Option(name="-hprof", usage="The filesystem path pointing to the hprof file to dump", required=true)
	private String hprofPath;
	
	@Option(name="-class", usage="The full class name of the instances to dump", required=true)
	private String classToDump;
	
	@Option(name="-delimeter", usage="String that separates all the columns", required=false)
	private String delimeter = "\t";
	
	@Option(name="-disableHeader", usage="Do not print the header column of the name of the fields", required=false)
	private boolean disableHeader = false;	
	
    public static void main(String[] args) throws IOException {
    	App bean = new App();
        CmdLineParser parser = new CmdLineParser(bean);
        try {
                parser.parseArgument(args);
                bean.run();
        } catch (CmdLineException e) {
            // handling of wrong arguments
            System.err.println(e.getMessage());
            parser.printUsage(System.err);
        }
    }
    
    public void run() throws FileNotFoundException, IOException {
	    Heap heap = HeapFactory.createHeap(new File(hprofPath));
	    
	    JavaClass javaClass = heap.getJavaClassByName(classToDump);
	    // unfortunately, the library does not use a generic
	    // but the javadoc guarentees it's a List on Instance. This also prevent us from inline
	    // the statement in the loop.
	    boolean needToWriteHeader = !disableHeader;
	    @SuppressWarnings("unchecked")  
		List<Instance> instances = javaClass.getInstances();
	    for(Instance instance : instances) {
	    	boolean first;
	    	
	    	@SuppressWarnings("unchecked") // same deal here
	    	List<FieldValue> fields = instance.getFieldValues();
	    	if(needToWriteHeader) {
	    		first = true;
		    	for(FieldValue field : fields) {
		    		if(!first) {
		    			System.out.print(delimeter);
		    		}
		    		
		    		System.out.print(field.getField().getName());
		    		
		    		first = false;
		    	}
		    	System.out.println();
		    	needToWriteHeader = false;
	    	}
	    	
    		first = true;
	    	for(FieldValue field : fields) {
	    		if(!first) {
	    			System.out.print(delimeter);
	    		}
	    		
	    		System.out.print(field.getValue());
	    		
	    		first = false;
	    	}
	    	System.out.println();
	    }
    }
}
