import org.netbeans.lib.profiler.heap.*;
import java.io.*;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws IOException {
	    if(args.length != 1) {
		    throw new IllegalArgumentException("hprof path missing.\nusage: App <hprofPath>");
	    }
	    String hprofPath = args[0];
	    File hprofFile = new File(hprofPath);

	    Heap heap = HeapFactory.createHeap(hprofFile);
    }

}
